### ISSUE TITLE
Klassifikation der Bibliographia Cartographica (BC)

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-data#29]
Die Klassifikation der [Bibliographia Cartographica (BC)](https://kxpt.k10plus.de/DB=1.67/) muss in BARTOC eingetragen und nach CSV konvertiert werden, um daraus JSKOS zu erzeugen: https://kxpt.k10plus.de/DB=1.67/START_SYSTEMATIK. 

Die Klassen bestehen nur aus level, notation und prefLabel. 

Für Cocoda ist ein SuchLink möglich:

https://kxpt.k10plus.de/DB=1.67/NOMAT=T/CLK?IKT=20&TRM={notation}

In einigen Fällen ist die Notation in der URL versteckt, z.B.

> * C: Persönlichkeiten der Kartographie
>   * [Biographie, Persönliches](https://kxpt.k10plus.de/DB=1.67/%24serverBase/DB=1.67/NOMAT=T/CLK?IKT=20&TRM=C.z)  (notation is C.z)

Als URIs schlage ich vor

* http://uri.gbv.de/terminology/bc (Vokabular)
* http://uri.gbv.de/terminology/bc/{notation} (einzelne Klassen)

Die CSV-Datei kann im Verzeichnis `bc` abgelegt werden.

**Comment by DavidBRohrer** [comment]
Die Klassifikation ist nun in Cocoda eingespielt.
