### ISSUE TITLE
Nomisma: Use dump instead of SPARQL query

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-data#3]
Related: https://github.com/gbv/cocoda/issues/200

**Comment by nichtich** [comment]
Nomisma is include via API, no data needed

**Comment by stefandesu** [comment]
I think the issue was that the data in jskos-data is requested via a SPARQL query and is not complete:

> Nomisma was now added to [jskos-data](https://github.com/gbv/jskos-data), but currently it's using the CSV output of a SPARQL request as a data source, meaning that not all data is included in the conversion. Eventually, it would be better to have either a SKOSMOS wrapper or to convert the RDF dump.

The first API entry for Nomisma in BARTOC is still our jskos-server instance which includes the above data. Nomisma is also available via BARTOC Skosmos, so if you mean that, we should change the order of the API entries in BARTOC.

**Comment by stefandesu** [comment]
Sorry, did not mean to reopen.
