### ISSUE TITLE
Nomisma: Add `toScheme` property to embedded mappings

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-data#43]
I noticed that our Nomisma data has a lot of embedded mappings, but only with properties `from`, `to`, and `type`. Assuming the `from` side is always the Nomisma concept, we still need `toScheme` in order to use the mappings. Not sure if this data is available in the source data; we might need to determine it based on the target URI of the mapping.

Edit: I forgot that at one point, we added scheme detection for embedded mappings, so in this case, I can imagine that we simply don't support any of the target vocabularies yet. I'll investigate though.

**Comment by nichtich** [comment]
Data has been updated to contain at least some `toScheme` (9247 of 22873 mappings).

**Comment by stefandesu** [comment]
Technically, this isn't needed (see my Edit above), but I think having the field makes it more "complete" in a way. Closing this issue now.
