### ISSUE TITLE
Add German prefLabel to nkostypes

### ISSUE THREAD

**Issue by stefandesu** [gbv/jskos-data#52]
Required for German interface of https://github.com/gbv/jskos-proxy.

**Comment by nichtich** [comment]
Data is in https://github.com/gbv/bartoc.org/blob/main/data/nkostype.concepts.ndjson an can be queried via https://bartoc.org/api

**Comment by stefandesu** [comment]
Is there an easy way to manage these inside this repository?

**Comment by nichtich** [comment]
The vocabulary is managed in DANTE so better use http://api.dante.gbv.de/voc/nkostype/top to get a current copy.
